version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '2022:5432'
    volumes:
       - ./src/docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fruits-pair-programming
    networks:
      - private  

networks:
  private:
    driver: bridge
